### PR TITLE
"Port" to ClojureScript

### PR DESCRIPTION
**Pull request by iantruslove**
I really want to use this lib to test the hiccup rendered by Reagent components, but it's just Clojure right now. 

This PR ports the source and tests over to CLJC, so it can target CLJ or CLJS.

The source file wasn't edited at all, it just worked with a simple rename.

The tests were trickier, only because Midje doesn't play nicely with CLJS. I didn't see a reasonable approach where I could have left the Midje tests in place, so I did as little as I could to replace them one to one with `clojure.test` tests. 

The rest of the PR is tooling to compile and run the tests in a CLJS target.

### CODE REVIEW

**Comment by magnars** [comment]
Looks good to me. What do you say, @cjohansen ?

**Comment by cjohansen** [comment]
👍 

I would argue that `0.5.0` is more appropriate than `0.4.1` for this kind of change, but that really is a minor point. Well done!

**Comment by cjohansen** [comment]
@iantruslove bump the version to 0.5.0 and I'll get it out there!

**Comment by iantruslove** [comment]
Happily. Thanks @magnars @cjohansen!

**Comment by cjohansen** [comment]
https://clojars.org/hiccup-find

**Pull request merged**
